- name: Install NFS client
  apt:
    name: nfs-common
    state: present

- name: Ensure mount directory exists.
  file:
    path: "{{ efs_mount_dir }}"
    state: directory
    mode: 0755

- name: Ensure EFS volume is mounted.
  mount:
    name: "{{ efs_mount_dir }}"
    src: "{{ efs_mount_point }}:/"
    fstype: nfs4
    opts: nfsvers=4.1
    state: mounted